services:
    db:
        image: mariadb:10.7.1
        ports:
            - 31006:3306
        env_file:
            - .env
        volumes:
            - ./db:/var/lib/mysql

    adminer:
        image: adminer:latest
        ports:
            - 31099:8080

    backend:
        image: sandwitches-backend
        build: .
        ports:
            - 31001:31001
        env_file:
          - .env
        depends_on:
          - db