services:
    db:
        image: mariadb:10.7.1
        ports:
            - 31006:3306
        env_file:
            - docker.env
        volumes:
            - ./db:/var/lib/mysql

    adminer:
        image: adminer:latest
        ports:
            - 31099:8080

    backend:
        image: sandwitches-backend
        build: ./express
        ports:
            - 31001:31001
        env_file:
            - ./express/docker.ormconfig.env
        depends_on:
            - db

    socket:
        image: sandwitches-socket
        build: ./socket
        ports:
            - 31002:31002
        depends_on:
            - backend
