services:
    db:
        # image: mysql:8.0.27
        image: mariadb:10.7.1
        ports:
            - 3309:3306
        env_file:
            - .env
        volumes:
            - ./db:/var/lib/mysql

    adminer:
        image: adminer:latest
        ports:
            - 9999:8080
