services:
    mariadb:
        image: mariadb:latest
        ports:
            - 3306:3306
        env_file:
            - .env
        volumes:
            - ./db:/var/lib/mysql

    adminer:
        image: adminer:latest
        ports:
            - 9999:8080
