name: Docker Image CI Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build express Docker image
      run: docker build ./backend --file ./backend/express/Dockerfile --tag esandwitches-backend-express:$(date +%s)
      
    - name: Build socket Docker image
      run: docker build ./backend --file ./backend/socket/Dockerfile --tag esandwitches-backend-socket:$(date +%s)
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_TOKEN }}
      
    
